[template]
cargo_generate_version = ">=0.17.4"
ignore = [".git", ".github", "README.md"]

[placeholders.mcu]
type = "string"
prompt = "Which MCU to target?"
choices = ["STM32F103C6", "STM32F103C8", "STM32F103RC", "STM32F103RB"]
default = "STM32F103C8"

[placeholders.panic_crate]
type = "string"
prompt = "Which panic crate to target?"
choices = ["panic_semihosting", "panic_halt", "panic_rtt_target", "panic_probe"]
default = "panic_semihosting"

[conditional.'defmt'.placeholders]
type = "bool"
prompt = "Enable defmt logging?"
default = false

[conditional.'defmt_format_custom'.placeholders]
type = "bool"
prompt = "Enable custom defmt format?"
default = false
